# Generated by Django 4.1 on 2022-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0002_report_institution_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='institution_level',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Kecamatan', 'Kecamatan'), ('Desa/Kelurahan', 'Desa/Kelurahan')], max_length=100),
        ),
    ]
