# Generated by Django 4.1 on 2022-10-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0002_remove_report_admin_remove_report_user_and_more'),
        ('submission_form', '0003_alter_report_institution_level'),
    ]

    operations = [
    ]
