# Generated by Django 4.1 on 2022-10-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0004_merge_20221031_0620'),
        ('submission_form', '0004_merge_20221031_1351'),
    ]

    operations = [
    ]
