# Generated by Django 4.1 on 2022-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_body', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
