# Generated by Django 4.1 on 2022-10-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_comments_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commenter_body',
            new_name='comment',
        ),
    ]
