# Generated by Django 4.1 on 2022-10-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_reviews_delete_comments_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(5, 'very good'), (4, 'good'), (3, 'mediocre'), (2, 'bad'), (1, 'very bad')], null=True),
        ),
    ]
