# Generated by Django 4.1 on 2022-11-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Mediocre'), (2, 'Bad'), (1, 'Very Bad')], null=True),
        ),
    ]
