# Generated by Django 4.1 on 2022-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Positif', 'Positif'), ('Negatif', 'Negatif')], max_length=100),
        ),
    ]
