# Generated by Django 4.1 on 2022-10-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
    ]
