# Generated by Django 4.1 on 2022-10-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_things', '0002_rename_is_active_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
