# Generated by Django 4.1 on 2022-10-28 02:24

from django.db import migrations, models
import login_things.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_things', '0003_alter_user_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(max_length=20, unique=True, validators=[login_things.models.validate_length]),
        ),
    ]
